[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# This ensures Netlify can properly handle pull requests
[context.pull-request]
  command = "npm run build"

# Handle netlify pull request previews properly
[context.deploy-preview]
  command = "npm run build"

# Optional: Set up branch deploys if needed
[context.branch-deploy]
  command = "npm run build"

# Default context is production
[context.production]
  command = "npm run build"
